export const cuisineList=[
    "Biryani",
    "Butter Chicken",
    "Paneer Tikka",
    "Chicken Biryani",
    "Mushroom Kebab",
    "Vegetable Curry",
    "Desserts",
    "Burgers",
    "Fries",
    "Dal Bhat",
    "Masala Dosa",
    "non-veg",
    "salad",
    "Idli",
    "Healthy",
    "Chole Bhature",
    "Palak Paneer",
    "Dhokla",
    "Sushi",
    "cafe",
    "Italian",
    "spanish",
    "Indian",
    "Japanese",
    "Samosa",
    "Pani Puri/Golgappa",
    "Tandoori Chicken",
    "Hyderabadi Biryani",
    "Pav Bhaji",
    "japanese",
    "Chicken Tikka Masala",
    "Gulab Jamun",
    "Idli Sambar",
]