export const cuisineList=[
    "Biryani",
    "Butter Chicken",
    "Paneer Tikka",
    "Chicken Biryani",
    "Mushroom Kebab",
    "Vegetable Curry",
    "Desserts",
    "Burgers",
    "Fries",
    "Dal Bhat",
    "Masala Dosa",
    "Rogan Josh",
    "Chole Bhature",
    "Palak Paneer",
    "Dhokla",
    "Aloo Gobi",
    "Samosa",
    "Pani Puri/Golgappa",
    "Tandoori Chicken",
    "Rasgulla",
    "Hyderabadi Biryani",
    "Vada Pav",
    "Pav Bhaji",
    "Dal Makhani",
    "Chicken Tikka Masala",
    "Gulab Jamun",
    "Idli Sambar",
]